### ISSUE TITLE
Ödeme Sayfasından kredi kartı bilgi girişi

### ISSUE THREAD

**Issue by mdaskin** [kahvedigital/iyzico-magento#2]
merhaba
eklenti mevcut durumda sipariş oluşturulduktan sonra ayrı sayfaya yönlendirmesi çok kullanışlı değil
opencart eklentisinde olduğu gibi ödeme sayfasında js ile açılması daha kullanışlı olacağını düşünüyorum

 
![untitled](https://cloud.githubusercontent.com/assets/10865015/23973660/d5ee8a98-09df-11e7-81bb-4727d9b77363.png)

**Comment by kahvedigital** [comment]
Merhabalar,
Bir sonraki geliştirmemizde tek sayfa için çalışmamız olacak.
