### ISSUE TITLE
Warning: include(Iyzipay\Options.php): failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by snowcore** [kahvedigital/iyzico-magento#3]
Hi

I have installed the module on Magento 1.9.3.1, and when I try to place an order, I get the following error:
`Warning: include(Iyzipay\Options.php): failed to open stream: No such file or directory  in lib/Varien/Autoload.php on line 94`

**Comment by regeditt** [comment]
merhaba acabaa  magento 1.9.3 sürümnde çalışıyormu eklentiniz..?

**Comment by kahvedigital** [comment]
Merhabalar, 
Geliştirme Test ortamında Magento ver. 1.9.3.1 Kullanmaktayız sorunsuz şekilde çalışmaktadır.
