### ISSUE TITLE
Odeme sonrasi hata

### ISSUE THREAD

**Issue by dekoz** [kahvedigital/iyzico-magento#9]
Merhabalar
Basarili odeme sonrasinda bu hatayi aliyorum.

a:5:{i:0;s:160:"Cannot send headers; headers already sent in /home/website/public_html/app/code/community/IyzicoCheckoutForm/IyzicoCheckoutForm/Model/IyziCardSaveLog.php, line 1";i:1;s:1564:"#0 /home/website/public_html/lib/Zend/Controller/Response/Abstract.php(148): Zend_Controller_Response_Abstract->canSendHeaders(true)
#1 /home/website/public_html/app/code/core/Mage/Core/Controller/Response/Http.php(107): Zend_Controller_Response_Abstract->setRedirect('https://www.dek...', 302)
#2 /home/website/public_html/app/code/community/IyzicoCheckoutForm/IyzicoCheckoutForm/controllers/ResponseController.php(155): Mage_Core_Controller_Response_Http->setRedirect('https://www.dek...')
#3 /home/website/public_html/app/code/community/IyzicoCheckoutForm/IyzicoCheckoutForm/controllers/ResponseController.php(71): IyzicoCheckoutForm_IyzicoCheckoutForm_ResponseController->_getPostResponseActionUrl(Object(MGS_Deals_Model_Order), Object(Iyzipay\Model\CheckoutForm), '1')
#4 /home/website/public_html/app/code/core/Mage/Core/Controller/Varien/Action.php(418): IyzicoCheckoutForm_IyzicoCheckoutForm_ResponseController->handleIyzicoPostResponseAction()
#5 /home/website/public_html/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('handleIyzicoPos...')
#6 /home/website/public_html/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#7 /home/website/public_html/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#8 /home/website/public_html/app/Mage.php(683): Mage_Core_Model_App->run(Array)
#9 /home/website/public_html/index.php(89): Mage::run('', 'store')
#10 {main}";s:3:"url";s:53:"/iyzicocheckoutform/response/handleIyzicoPostResponse";s:11:"script_name";s:10:"/index.php";s:4:"skin";s:2:"tr";}

**Comment by dekoz** [comment]
PHP Version 7.1.14
Magento vers. 1.9.3.7

**Comment by kahvedigital** [comment]
Merhabalar,
Detaylı inceleyebilmemiz için iletişime geçip bizden destek alabilirsiniz.

**Comment by ayhankerim** [comment]
Bu sorun bende de oluştu. kerimayhan@gmail.com iletişime geçebilir misiniz?

**Comment by kahvedigital** [comment]
Mail ile geri dönüş yapıldı.

**Comment by erhanky** [comment]
bizde de aynı sorun oldu. erhanky@gmail.com bilgilendirme yapabilirseniz sevinirim.
